/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.g1m3.redflix.vistas;
import com.g1m3.redflix.*;
import com.g1m3.redflix.modelos.*;
import com.g1m3.redflix.repos.*;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ControlCRUD extends javax.swing.JFrame {

   PeliculasRepo RepoP;
     
    
    public ControlCRUD() {
        initComponents();
        String[] args={};
        RedflixApplication.runSpringServer(args);
        
        RepoP =Extractor.getBean(PeliculasRepo.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Guardar = new javax.swing.JButton();
        Button_Actualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID_variable_P = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ID_var_dir_p = new javax.swing.JTextField();
        Titulo_Variable_P = new javax.swing.JTextField();
        year_variable_p = new javax.swing.JTextField();
        Dir_var_p = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resumen_variable_p = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ID_buscador_P = new javax.swing.JTextField();
        titulo_buscador_p = new javax.swing.JTextField();
        Button_buscar = new javax.swing.JButton();
        Button_Borrado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SALIDA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Button_Guardar.setText("Guardar");
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });

        Button_Actualizar.setText("Actualizar");
        Button_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ActualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        jLabel3.setText("Titulo:");

        jLabel4.setText("Resumen:");

        jLabel5.setText("ID director:");

        jLabel6.setText("Director:");

        ID_variable_P.setText("Ejemplo: 1111");
        ID_variable_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_variable_PActionPerformed(evt);
            }
        });

        jLabel7.setText("Año:");

        ID_var_dir_p.setText("Ejemplo 2222");
        ID_var_dir_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_var_dir_pActionPerformed(evt);
            }
        });

        Titulo_Variable_P.setText("Ejemplo: piratas del caribe");
        Titulo_Variable_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titulo_Variable_PActionPerformed(evt);
            }
        });

        year_variable_p.setText("Ejemplo: 2014");

        Dir_var_p.setText("Ejemplo:  Quentin Tarantino");
        Dir_var_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dir_var_pActionPerformed(evt);
            }
        });

        Resumen_variable_p.setColumns(20);
        Resumen_variable_p.setRows(5);
        jScrollPane1.setViewportView(Resumen_variable_p);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        jLabel8.setText("REDFLIX- TABLA PELICULAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Dir_var_p, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ID_var_dir_p, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(43, 43, 43))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Titulo_Variable_P, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(year_variable_p, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                                    .addComponent(ID_variable_P))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Guardar)
                        .addGap(88, 88, 88)
                        .addComponent(Button_Actualizar)
                        .addGap(168, 168, 168))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ID_variable_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_Variable_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year_variable_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ID_var_dir_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Dir_var_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Actualizar)
                    .addComponent(Button_Guardar))
                .addGap(76, 76, 76))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 13)); // NOI18N
        jLabel1.setText("  BUSCADOR DE PELICULAS");

        jLabel9.setText("ID");

        jLabel10.setText("Titulo");

        ID_buscador_P.setText("Ejemplo: 2222");
        ID_buscador_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_buscador_PActionPerformed(evt);
            }
        });

        titulo_buscador_p.setText("Ejemplo: piratas del caribe");
        titulo_buscador_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulo_buscador_pActionPerformed(evt);
            }
        });

        Button_buscar.setText("Buscar");
        Button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_buscarActionPerformed(evt);
            }
        });

        Button_Borrado.setText("Borrar");
        Button_Borrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_BorradoMouseClicked(evt);
            }
        });
        Button_Borrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BorradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ID_buscador_P)
                    .addComponent(titulo_buscador_p, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_buscar)
                    .addComponent(Button_Borrado))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_buscador_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Button_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(titulo_buscador_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Borrado))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        SALIDA.setColumns(20);
        SALIDA.setRows(5);
        jScrollPane2.setViewportView(SALIDA);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel11.setText("Salida de Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Dir_var_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dir_var_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dir_var_pActionPerformed

    private void Titulo_Variable_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titulo_Variable_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titulo_Variable_PActionPerformed

    private void Button_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ActualizarActionPerformed

        long w = Long.parseLong(ID_variable_P.getText());
        Optional<Peliculas> consulta3 = RepoP.findById(w);
        Optional<Peliculas> consulta4 = RepoP.findById(w);
        if (consulta3.isPresent()) {

            Peliculas pl2 = consulta3.get();
            Peliculas pl3 = consulta4.get();

            pl2.setTitulo_contenido(Titulo_Variable_P.getText());//almacenado tipo 
            pl2.setPel_resumen(Resumen_variable_p.getText());
            pl2.setPel_fecha(Integer.parseInt(year_variable_p.getText()));
            pl2.setId_director(Integer.parseInt(ID_var_dir_p.getText()));
            pl2.setPel_nom_director(Dir_var_p.getText());
            
            SALIDA.setText("\nSe Actualizaron los siguientes datos\n\n\n"
                    
                    +"Antes:\n"
                    + "ID pelicula: "+pl3.getId_pelicula()+"\n"
                    +"Titulo Pelicula: "+ pl3.getTitulo_contenido()+"\n"
                    +"Resumen: "+ pl3.getPel_resumen()+"\n"
                    +"Año: " + pl3.getPel_fecha()+"\n"
                    +"ID director: " + pl3.getId_director()+"\n"
                    +"Director: " + pl3.getPel_nom_director()+"\n"
                    
                    +"\n\nAhora:\n"
                    + "ID pelicula: "+pl2.getId_pelicula()+"\n"
                    +"Titulo Pelicula: "+ pl2.getTitulo_contenido()+"\n"
                    +"Resumen: "+ pl2.getPel_resumen()+"\n"
                    +"Año: " + pl2.getPel_fecha()+"\n"
                    +"ID director: " + pl2.getId_director()+"\n"
                    +"Director: " + pl2.getPel_nom_director()+"\n");
            
            RepoP.save(pl2);

        }else {
             SALIDA.setText("No se Encuentra la pelicula Con el ID: " + w);

        }

    }//GEN-LAST:event_Button_ActualizarActionPerformed

    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed


        Peliculas pl = new Peliculas();//declaracion tipo contenido 
        
        pl.setId_pelicula(Long.parseLong(ID_variable_P.getText()));//almacenado titulo
        pl.setTitulo_contenido(Titulo_Variable_P.getText());//almacenado tipo 
        pl.setPel_resumen(Resumen_variable_p.getText());
        pl.setPel_fecha(Integer.parseInt(year_variable_p.getText()));
        pl.setId_director(Integer.parseInt(ID_var_dir_p.getText()));
        pl.setPel_nom_director(Dir_var_p.getText());
        
        RepoP.save(pl);
        
        SALIDA.setText("\nSe guardaron los siguientes datos\n\n\n"
                    + "ID pelicula: "+pl.getId_pelicula()+"\n"
                    +"Titulo Pelicula: "+ pl.getTitulo_contenido()+"\n"
                    +"Resumen: "+ pl.getPel_resumen()+"\n"
                    +"Año: " + pl.getPel_fecha()+"\n"
                    +"ID director: " + pl.getId_director()+"\n"
                    +"Director: " + pl.getPel_nom_director()+"\n");
        
    }//GEN-LAST:event_Button_GuardarActionPerformed

    private void Button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_buscarActionPerformed
       
        long x = Long.parseLong(ID_buscador_P.getText());
        Optional<Peliculas> consulta = RepoP.findById(x);
        if (consulta.isPresent()) {
            
            Peliculas llamado = consulta.get();// llama la consulta y lo guarda en un tipo contendio
            
            SALIDA.setText("\nConsulta\n\n\n"
                    + "ID pelicula: "+llamado.getId_pelicula()+"\n"
                    +"Titulo Pelicula: "+ llamado.getTitulo_contenido()+"\n"
                    +"Resumen: "+ llamado.getPel_resumen()+"\n"
                    +"Año: " + llamado.getPel_fecha()+"\n"
                    +"ID director: " + llamado.getId_director()+"\n"
                    +"Director: " + llamado.getPel_nom_director()+"\n");
        } else {
             SALIDA.setText("No se Encuentra la pelicula Con el ID: " + x);

        }
        
     
        
    }//GEN-LAST:event_Button_buscarActionPerformed

    private void ID_var_dir_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_var_dir_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_var_dir_pActionPerformed

    private void ID_buscador_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_buscador_PActionPerformed
              
    }//GEN-LAST:event_ID_buscador_PActionPerformed

    private void titulo_buscador_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulo_buscador_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulo_buscador_pActionPerformed

    private void Button_BorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BorradoActionPerformed
        
        long y = Long.parseLong(ID_buscador_P.getText());
        Optional<Peliculas> consulta2 = RepoP.findById(y);
        if (consulta2.isPresent()) {
            
            Peliculas llamado2 = consulta2.get();// llama la consulta y lo guarda en un tipo contendio
            
            SALIDA.setText("Se Borro la pelicula: "+llamado2.getTitulo_contenido());
            
            RepoP.delete(llamado2);
            
            
        } else {
             SALIDA.setText("No se Encuentra la pelicula Con el ID: " + y);

        }
        
    }//GEN-LAST:event_Button_BorradoActionPerformed

    private void ID_variable_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_variable_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_variable_PActionPerformed

    private void Button_BorradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_BorradoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_BorradoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Actualizar;
    private javax.swing.JButton Button_Borrado;
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_buscar;
    private javax.swing.JTextField Dir_var_p;
    private javax.swing.JTextField ID_buscador_P;
    private javax.swing.JTextField ID_var_dir_p;
    private javax.swing.JTextField ID_variable_P;
    private javax.swing.JTextArea Resumen_variable_p;
    private javax.swing.JTextArea SALIDA;
    private javax.swing.JTextField Titulo_Variable_P;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField titulo_buscador_p;
    private javax.swing.JTextField year_variable_p;
    // End of variables declaration//GEN-END:variables
}
